version: "3"
services:
  authors:
    build: ./authors
    container_name: authors-service
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks:
      - mynet
  books:
    build: ./books
    container_name: books-service
    ports:
      - 8082:8082
    networks:
      - mynet
    depends_on:
      - redis
  frontend:
    build: ./frontend
    container_name: frontend-service
    ports:
      - 8083:8083
    networks:
      - mynet
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - mynet

networks:
  mynet:
